# Generated by Django 3.2 on 2022-08-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('building', models.CharField(max_length=32)),
                ('room', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('sclass', models.CharField(max_length=32)),
                ('xueyuan', models.CharField(max_length=32)),
                ('year', models.CharField(max_length=32)),
                ('lxfs', models.CharField(max_length=32)),
                ('islouzhang', models.BooleanField()),
                ('tid', models.CharField(max_length=32)),
            ],
        ),
    ]
