# Generated by Django 3.2 on 2022-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuCovid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('bid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=32)),
                ('louzhang', models.CharField(max_length=32)),
                ('iscomlished', models.BooleanField(default=False)),
                ('isqueue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CovidNotice',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('info', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('denum', models.CharField(max_length=32)),
                ('sid', models.CharField(max_length=8)),
                ('date', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('result', models.BooleanField()),
                ('path', models.CharField(max_length=100)),
                ('jcfs', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PicStore',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('imgsrc', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('lxfs', models.CharField(max_length=32)),
            ],
        ),
    ]
