# Generated by Django 3.2 on 2022-08-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuCovid', '0002_building_covidnotice_detection_picstore_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='iscomlished',
            new_name='iscomplished',
        ),
    ]
