# Generated by Django 3.2 on 2022-05-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('bid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=32)),
                ('louzhang', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=8)),
                ('date', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('result', models.BooleanField()),
                ('path', models.CharField(max_length=100)),
                ('jcfs', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PicStore',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('imgsrc', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('building', models.CharField(max_length=32)),
                ('room', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('sclass', models.CharField(max_length=32)),
                ('xueyuan', models.CharField(max_length=32)),
                ('year', models.CharField(max_length=32)),
                ('lxfs', models.CharField(max_length=32)),
                ('islouzhang', models.BooleanField()),
                ('tid', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('lxfs', models.CharField(max_length=32)),
            ],
        ),
    ]
