# Generated by Django 3.2 on 2022-05-31 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kangyuan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='tid',
            new_name='tidx',
        ),
    ]
